### ISSUE TITLE
 'Namespace' object has no attribute 'data_path'

### ISSUE THREAD

**Issue by zky-66** [chen-hhaa/SW-WaveNet4ASD#2]
Traceback (most recent call last):
  File "/home/zky/ST/sw_wavenet/main.py", line 131, in <module>
    auc, pauc = run(args)
  File "/home/zky/ST/sw_wavenet/main.py", line 115, in run
    auc, p_auc = eval_v2(model, args)
  File "/home/zky/ST/sw_wavenet/train_utils.py", line 81, in eval_v2
    dirs = utils.select_dirs(args.data_path, data_type='')
AttributeError: 'Namespace' object has no attribute 'data_path'

Hello author，The problem occurred while running the code. I'd like to ask where this "data_path" is located. Is it for evaluating the training set?

**Comment by webbrain-one** [comment]
Hi, thanks for reporting this! I opened a pull request to fix it by adding the missing `data_path` argument used by `eval_v2` to locate the evaluation data. PR: https://github.com/chen-hhaa/SW-WaveNet4ASD/pull/4
